### ISSUE TITLE
error mysql

### ISSUE THREAD

**Issue by Muhtarhan27** [shyamjos/deploy-mysql-cluster#1]
ok: [mysql_node_3] => (item=galera-4)
ok: [mysql_node_3] => (item=galera-arbitrator-4)
failed: [mysql_node_3] (item=mysql-wsrep-8.0) => {"ansible_loop_var": "item", "cache_update_time": 1677841061, "cache_updated": true, "changed": false, "item": "mysql-wsrep-8.0", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'mysql-wsrep-8.0=8.0.30-26.11+1ubuntu20.04'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n mysql-wsrep-8.0 : Depends: mysql-wsrep-server (= 8.0.30-26.11+1ubuntu20.04) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " mysql-wsrep-8.0 : Depends: mysql-wsrep-server (= 8.0.30-26.11+1ubuntu20.04) but it is not going to be installed"]}
ok: [mysql_node_3] => (item=rsync)

**Comment by shyamjos** [comment]
You may try upgrading the packages in the playbook to fix this issue , I am closing this since I no longer support this project
